<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FleetTrack.Application\FleetTrack.Application.csproj" />
    <ProjectReference Include="..\FleetTrack.Domain\FleetTrack.Domain.csproj" />
  </ItemGroup>

</Project>
