<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Endpoints\" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\FleetTrack.Application\FleetTrack.Application.csproj" />
	</ItemGroup>
</Project>